### ISSUE TITLE
readtimearray needs to handle more formats

### ISSUE THREAD

**Issue by LeoK987** [JuliaStats/TimeSeries.jl#105]
Currently, the following format can not be correctly handled.
````
<Date>, <Time>, <Open>, <High>, <Low>, <Close>, <Volume>
2010/1/4,9:01:00,7300,7330,7300,7316,8706
2010/1/4,9:02:00,7316,7322,7298,7302,12764
````
If there is no objections, I plan to add a default parameter TimeCols=1 for the function, so that it becomes:

function readtimearray(fname::String; TimeCols=1)

Also the function assumes the existence of a header line in the file.  That needs to be taken care of.

**Comment by multidis** [comment]
Implemented in https://github.com/JuliaStats/TimeSeries.jl/pull/180

**Comment by milktrader** [comment]
Closing this with the new feature of a kwarg that allows formats to be specified in the `format` kwarg.

**Comment by milktrader** [comment]
Re-opening to have this serve as an edge case that fails the current regex parsing.

**Comment by milktrader** [comment]
Ok, re-closing this. I'm using this data in testing but have modified it by removing two columns of Date (one for Date and one for Time) and combined them with a space delimiter. 

I think it's reasonable to pre-process the data to include all of the datetime information in a single column.
