### ISSUE TITLE
Should column names be symbols?

### ISSUE THREAD

**Issue by hayd** [JuliaStats/TimeSeries.jl#134]
DataFrames.jl allows only symbol column names, whilst it looks like TimeSeries column names must be UTF8String.

https://github.com/JuliaStats/DataFrames.jl/pull/509

**Comment by milktrader** [comment]
Not sure the pros outweigh the cons. Some developments in Base https://github.com/JuliaLang/julia/issues/9945#issuecomment-71923264

Closing for now.
