### ISSUE TITLE
Multiple time-series

### ISSUE THREAD

**Issue by shashi** [JuliaStats/TimeSeries.jl#157]
I have got a single database with time-series data over a period from multiple (varying) number of sources. The data has the following layout:

```csv
source_id, date, col1, col2
1,2014-12-20,0.324,0.432
1,2014-12-21,0.324,0.432
... more dates for source 1
2,2014-12-20,0.904,0.234
2,2014-12-21,0.239,0.245
... more dates for source 2
```

How would a workflow which extracts this from the CSV into `TimeSeries` data structures look like?

I am to do the same analyses on all of the sources, and there are thousands of them. From what I can see from the documentation and examples, I infer the way to deal with this is create those many TimeArrays and map over them to do the analyses... Is there a better way to talk about multiple sources? If not, could there be?

**Comment by milktrader** [comment]
If you 'merge' individual time series, you'll get the mega TimeArray. An added benefit is that there is now a constraint that column names cannot duplicate and each new name is appended with`_n` where n is the number of duplicates.
