### ISSUE TITLE
Do we enforce timestamp to be unique and ordered?

### ISSUE THREAD

**Issue by tonyhffong** [JuliaStats/TimeSeries.jl#158]
from the implementation of `.+` etc, it doesn't seem to take advantage that it might be, nor do we have an efficient (binary search) test of the existence of a date/time in the TimeArray.

**Comment by milktrader** [comment]
timestamp has to be unique and ordered per the inner constructor

````julia
# some initial conditions
 timestamp != unique(timestamp) ? error("there are duplicate dates"):
 ~(flipud(timestamp) == sort(timestamp) || timestamp == sort(timestamp)) ? error("dates are mangled"):
# some other checks then construction of object
````

**Comment by milktrader** [comment]
Not sure about your point regarding the `.+` operator though

**Comment by tonyhffong** [comment]
I'm referring to this code in apply.jl
```julia
for op in [:.+, :.-, :.*, :./]
  @eval begin
    function ($op){T,N}(ta1::TimeArray{T,N}, ta2::TimeArray{T,N})
      cname  = [ta1.colnames[1][1:2] *  string($op) *  ta2.colnames[1][1:2]]
      tstamp = Date[]
      vals   = T[]
      for i in 1:size(ta1.timestamp, 1)
        for j in 1:size(ta2.timestamp, 1)
          if ta1.timestamp[i] == ta2.timestamp[j] 
            push!(tstamp, ta1.timestamp[i]) 
            push!(vals, ($op)(ta1.values[i], ta2.values[j])) 
          end
        end
      end
      TimeArray(tstamp, vals, cname)
    end # function
  end # eval
end # loop
```
If the timestamps are already ordered, this could be a O(N) algorithm instead of a O(N^2) algorithm.

**Comment by milktrader** [comment]
Needless to say I'd like to see that. I recall not finding a good solution to creating empty arrays and pushing into them.

**Comment by GordStephen** [comment]
Borrowing heavily from the [`merge` implementation](https://github.com/JuliaStats/TimeSeries.jl/blob/master/src/combine.jl#L28), would something along these lines work?

```julia
for op in [:.+, :.-, :.*, :./]
  @eval begin
    function ($op){T,N}(ta1::TimeArray{T,N}, ta2::TimeArray{T,N})
      cname  = [ta1.colnames[1][1:2] *  string($op) *  ta2.colnames[1][1:2]]
      idx1, idx2 = overlaps(ta1.timestamp, ta2.timestamp)
      # obtain shared timestamp
      tstamp = ta1[idx1].timestamp
      # retrieve values that match the Int array matching dates
      vals1  = ta1[idx1].values
      vals2  = ta2[idx2].values
      N = size(vals1, 1)
      vals = Array(T, N, 1)
      for i in 1:N
        vals[i] = ($op)(ta1.values[i], ta2.values[i])
      end
      TimeArray(tstamp, vals, cname)
    end # function
  end # eval
end # loop
```

**Comment by milktrader** [comment]
Could you time your version against the existing one?

**Comment by milktrader** [comment]
Here is some data to work with ...

````julia
using MarketData

merge(AAPL, BA) # different number of rows

merge(BA, CAT) # same number of rows
````

**Comment by GordStephen** [comment]
Using `master` branch (with the `Date[]` -> `DateTime[]` hack/patch mentioned in https://github.com/JuliaStats/TimeSeries.jl/issues/190):
```
@elapsed (data["WndSpNS"].^2 .+ data["WndSpWE"].^2).^0.5
53.242452311
```
Using `linearops` branch (version above):
```
julia> @elapsed (data["WndSpNS"].^2 .+ data["WndSpWE"].^2).^0.5
0.12954737
```

Testing with a ~20,000-row TimeArray, on the 3rd execution of each expression to eliminate compile time.

**Comment by GordStephen** [comment]
Testing with non-aligned rows:
`master`:
```
julia> @elapsed (data["WndSpNS"][1:10000].^2 .+ data["WndSpWE"][5000:15000].^2).^0.5
14.29950785
```
`linearops`:
```
julia> @elapsed (data["WndSpNS"][1:10000].^2 .+ data["WndSpWE"][5000:15000].^2).^0.5
0.096756729
```

**Comment by milktrader** [comment]
Wow, that's pretty cool. Since you're in your own branch, can you run this to see if tests still pass?

````julia
julia> using FactCheck

julia> include(Pkg.dir("TimeSeries/test/apply.jl"))
````

**Comment by milktrader** [comment]
Also, I'm wondering what commit you're working on. Probably get the latest and then a PR would be awesome.

**Comment by GordStephen** [comment]
Tests still pass. I just copy-pasted the overlaps function from combine.jl into apply.jl, which I suppose isn't ideal... I'm not sure what the best way to share functions between files is?

**Comment by milktrader** [comment]
Well if we use `overlaps` in different files we should create a "utilities.jl" file and put it there, since it's not a good candidate for exporting. If you do a PR, I can edit it.

**Comment by GordStephen** [comment]
Ok, PR done. I also implemented `!` and `.!=` between TimeArrays, I'll write some tests and do another PR with those.

**Comment by milktrader** [comment]
Sounds good. I'll close this since I added to it and it created a separate PR.

**Comment by milktrader** [comment]
https://github.com/JuliaStats/TimeSeries.jl/pull/192
