### ISSUE TITLE
Interpolation?

### ISSUE THREAD

**Issue by tonyhffong** [JuliaStats/TimeSeries.jl#166]
Should interpolation part of a timeseries' data structure? (error, zero, linear, step, lambda) or should we simply have an `interpolate` function with this preference?

**Comment by milktrader** [comment]
How about start with an `interpolate` method with the kwargs and then see if it makes sense to break it out. 

I'm adding a metadata field soon which may create some near-term turmoil, even with tests passing. This will bump the version up a minor increment. Just a quick heads up before you start on this if that's your plan.

**Comment by milktrader** [comment]
Closing this because it's older.
