### ISSUE TITLE
getindex does not preserve metadata

### ISSUE THREAD

**Issue by multidis** [JuliaStats/TimeSeries.jl#168]
Extracting `TimeArray` column results in metadata loss; may be the case for other getindex-methods and percentchange-function:

    using TimeSeries, MarketData, FinancialSeries
    Apple = TimeArray(AAPL.timestamp, AAPL.values, AAPL.colnames, Stock(Ticker("AAPL"))
    Apple["Close"].meta

**Nothing (constructor with 1 method)**
(instead of preserving the stock-metadata).

**Comment by milktrader** [comment]
closed with #170
