### ISSUE TITLE
Modify show method to enable code reuse

### ISSUE THREAD

**Issue by multidis** [JuliaStats/TimeSeries.jl#172]
Split `show`-method for `TimeArray` into the summary line part and a helper function for the rest of the printing. That way, when writing show methods for alias-types (e.g. `FinancialTimeSeries`), only new summary line code would be needed and the same helper function would then be called from `TimeSeries.jl`.

**Comment by milktrader** [comment]
Interesting idea. This is presumably to avoid code duplication in packages that depend on TimeSeries such as FinancialSeries, no? 

Does this affect the default show for TimeArrays?

**Comment by multidis** [comment]
No, this would not affect the default show. Only simplifies writing more specific show-methods. I was just tweaking the `Blotter` show, and except for the summary line it duplicates TimeArray default. Same happened with FinancialSeries.

**Comment by milktrader** [comment]
Alright, I'm on board.

**Comment by milktrader** [comment]
Closing because this is old and we haven't made progress fleshing this idea out. Please re-open if there is still some interest.
