### ISSUE TITLE
show error in Julia 0.3

### ISSUE THREAD

**Issue by multidis** [JuliaStats/TimeSeries.jl#178]
using MarketData
    AAPL

ERROR: `round` has no method matching round(::Type{Integer}, ::Float64)
 in show at /home/...../.julia/v0.3/TimeSeries/src/timearray.jl:99
 
Julia 0.3 is currently the recommended version for most users. Some `round`, `ceil/floor` etc. functions may have been changing in 0.4 development.

**Comment by milktrader** [comment]
yep, `round` is the new `iround` in show.jl

This calls for using the Compat package

**Comment by multidis** [comment]
Compat.jl is interesting, I was not aware of it. Since show is not a performance-critical method, perhaps that is something to try.

**Comment by milktrader** [comment]
I'll revert this show back to v0.3 later today.

**Comment by milktrader** [comment]
d39db57c09df9698eea9cd02b8ea580ade341dd reverts to `v0.3` compatible show method use of `iround` which is deprecated in `v0.4` in favor of `round`
