### ISSUE TITLE
Operations between DateTime-indexed timeseries

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#190]
Mathematical and comparison operations between two TimeArrays using a DateTime index (rather than a Date index) return `ERROR: there are duplicate dates`. This would appear to stem from the fact that the output TimeArray index is initialized as a Date, throwing away the intra-day time data when populating the output array.

For my purposes replacing `tstamp = Date[]` with `tstamp = DateTime[]` on the relevant lines ([1](https://github.com/JuliaStats/TimeSeries.jl/blob/master/src/apply.jl#L14
), [2](https://github.com/JuliaStats/TimeSeries.jl/blob/master/src/apply.jl#L89)) resolves the issue, but I imagine a more general solution would be desirable - maybe checking that the series indices are of the same type and then using that type for the output timeseries index?

(Also, the O(n^2) complexity of the operation becomes an issue with long series... but I guess that's a different issue.)

**Comment by GordStephen** [comment]
`findwhen` also assumes Date-indexing and outputs a vector containing repeated Dates when used on DateTime-indexed data.

**Comment by GordStephen** [comment]
https://github.com/JuliaStats/TimeSeries.jl/pull/191 addresses the originally identified issue, but it looks like `to`, `from`, `findwhen`, and `collapse` all only work with Date indexing at the moment. When that changes it would probably be good for tests to reference both Date- and DateTime-indexed sample data (ie `datetime1`, `datetime2` in `MarketData`).

**Comment by milktrader** [comment]
Yes, thanks.

**Comment by GordStephen** [comment]
Status update: The issues with math/comparison operators have been addressed now, and #206 would fix `findwhen`, so `to`, `from`, and `collapse` are what's left to think about.

**Comment by GordStephen** [comment]
#223 now supports `to`, `from`, and `collapse` (as well as the other functions mentioned earlier) with non-Date TimeTypes (i.e. DateTimes)
