### ISSUE TITLE
Generalize value type from Array{T,N} to DenseArray{T,N}? 

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#194]
TimeArrays can't have BitArray contents at the moment. Moving allowed values up a step on the type hierarchy from `Array{T,N}` to `DenseArray{T,N}` would solve this (and also enable any other more obscure array types people might want to use) - thoughts?

**Comment by milktrader** [comment]
I wanted to add speculative tag but can't figure out this api. In any case, thanks for the idea.

**Comment by milktrader** [comment]
````julia
julia> Array <: DenseArray
true

julia> BitArray <: DenseArray
true

julia> BitArray <: Array
false
````

**Comment by GordStephen** [comment]
Relevant discussion has moved over to https://github.com/JuliaStats/TimeSeries.jl/pull/197
