### ISSUE TITLE
Refactor code base

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#196]
- [ ] replace Arrays with DenseArrays
- [ ] add Unary operators
- [ ] add Logical operators
- [ ] refactor column naming convention
- [ ] add BigInt, Signed and Unsigned to dispatch list
- [ ] other

I'm stubbing out `other` for now and will fill it out with the _other_ changes @GordStephen is proposing

**Comment by milktrader** [comment]
Besides the code, tests (which seem to be included) and documentation changes will need to be updated for the task to be marked complete.

**Comment by GordStephen** [comment]
These ideas (or some evolution of them) all ended up in https://github.com/JuliaStats/TimeSeries.jl/pull/205, so I'll go ahead and close this.
