### ISSUE TITLE
readtimearray when 1st field of 1st row is empty string

### ISSUE THREAD

**Issue by DannyZuko** [JuliaStats/TimeSeries.jl#198]
In case a csv file has the following form, 
````
"","ES1 Index","VG1 Index","TY1 Comdty","RX1 Comdty","GC1 Comdty"
"1999-01-04",1391.12,3034.53,66.515625,86.2,441.39
"1999-01-05",1404.86,3072.41,66.3125,86.17,440.63
"1999-01-06",1435.12,3156.59,66.4375,86.32,441.7
````
since the 1st field of the 1st row is an empty string, we get the following error:

ERROR: `convert` has no method matching convert(::Type{UTF8String}, ::Float64)
 in push! at array.jl:460
 in readtimearray at /home/juser/.julia/v0.3/TimeSeries/src/readwrite.jl:25

If we replace "" with "Dates", then it works fine. The issue might be at line 6-8 in readwrite.jl ?

**Comment by milktrader** [comment]
Yeah, the first line of the file is being wiped out with the empty-line code in lines 6-8 so the error is generated when you try converting `1391.12,3034.53,66.515625,86.2,441.39` into an array of UTF8String (which is designed for column names). 

I'll leave this open for now but the easiest solution is a bit of pre-processing in the manner you discovered. I can see the possibility though for more clever code that doesn't throw out the baby with the bath water.

**Comment by milktrader** [comment]
Closing this since it seems an edge case that can be easily handled with a small bit of pre-processing.
