### ISSUE TITLE
Final version supporting Julia 0.3 planned

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#202]
I'd like to tag one final version that *only* supports Julia 0.3 and then move on. The next version (released 10 minutes later) will support only Julia 0.4 with a ceiling of Julia 0.5. For TimeSeries, this gets rid of the transition of Dates.jl to Base control flow. It also abandons the Compat approach to compatibility. There are some other testing issues involving syntax in FactCheck (`=>` vs `-->`) that will be accommodated. 

One reason for this approach is fear and loathing from the impending doom of the Great Array Apocalypse that is planned to happen in Julia 0.5. The Mamba.jl package has been tagging versions with limits on Julia release support. I'd be interested in how that experiment has progressed @brian-j-smith

I will tag the final version of TimeSeries that supports Julia 0.3 soon, and then tag the next version that only supports Julia 0.4 shortly thereafter. The version that supports only Julia 0.4 will be enforced in the REQUIRE file with this line:

````
julia 0.4 0.5-
````
I'm not clear on how support for Julia 0.5 should be accommodated so I'm open to suggestions. One method that I'm leaning towards is the Mamba.jl approach. The question I have about the Mamba.jl approach is if you're limited to incrementing every tag, or if you can reserve `0.x` for one Julia version and continue tagging `0.y` for the next version.

**Comment by milktrader** [comment]
As a side note, once TimeSeries gets tagged as the last one supporting Julia 0.3, my downstream packages (Quandl.jl, MarketTechnicals.jl, MarketData.jl) will likewise be restricted. In these cases, the REQUIRE file will include the following 

````
julia 0.3 0.4-
TimeSeries 0.5 0.6 # assuming 0.6 will be the one that abandons support for Julia 0.3
...
````

**Comment by GordStephen** [comment]
Awesome. I have a new PR to submit so I'll wait to rebase against the 0.4+ version once it's available.

**Comment by milktrader** [comment]
Alright then, it looks like 82337d7b82855bb135c50f30cc04614b64bed243 is passing on Travis, so I'll wrap this up.

**Comment by milktrader** [comment]
Ok, it's tagged. Unfortunately I've lost privileges to commit to METADATA (which I hope is a temporary situation) so we'll have to wait for this to go through. It is passing the tests though.

**Comment by milktrader** [comment]
I made the mistake of building Julia 0.5 with my git setup so now I'm downloading the tar file for 0.4 and will build that once it's finished. This might take a while though. I've got a new branch for the future 0.6.0 but I can't test it without having 0.4

**Comment by brian-j-smith** [comment]
Hi @milktrader.  The Mamba.jl experiment with separate versions for julia 0.3 and 0.4 has been going smoothly.  Below is a short summary of what I ended up doing:

1. Mamba 0.4.x versions require julia 0.3, and are maintained in a separate ``release-0.4`` branch on the package's GitHub [site](https://github.com/brian-j-smith/Mamba.jl/).
2. Mamba 0.5.x and latter (currently on 0.6.1) have required julia 0.4, and are maintained in their respective branches (``release-0.5``, ``release-0.6``, ...).

From what I can tell ``Pkg.tag`` increments the most recent tag found in the branch from which it is called.  I have been using it fine to increment my different package versions.  Just need to take care to not increment an earlier version to a tag that overlaps with a later version.  Package tags and metadata can also be update manually (outside of julia) if something nonstandard needs to be done.

I was really hoping to maintain compatibility across julia 0.4 and 0.5 at least.  I haven't been keeping up with the plans for 0.5, but did see someone refer to it as "Arraymageddon".  Despite all the signs of impending doom, I may try some measure of programming to the lowest common denominator across julia releases and the Compat package to maintain compatibility.  My threshold for doing those things is pretty low, so I may end up moving on from julia 0.4 to 0.5 eventually.  However, I'll hold off on making that decision until 0.5 is close to being released.

**Comment by milktrader** [comment]
Thanks for the info @brian-j-smith !
