### ISSUE TITLE
Type parameter for Date vs DateTime?

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#207]
Thinking about how to approach the remaining issues in #190, it occurs to me that it would be useful to be able to define methods specific to Date- vs DateTime-indexed arrays. One approach might be to specify the TimeType as a TimeArray type parameter. The type definition might look something like:

```julia
immutable TimeArray{T,N,D<:TimeType,M} <: AbstractTimeSeries

    timestamp::Vector{D}
    values::AbstractArray{T,N}
    colnames::Vector{UTF8String}
    meta::M
```
One could then write things like:

```julia
function from{T,N,D}(ta::TimeArray{T,N,D}, starttime::D)
...
```
Any thoughts?

**Comment by milktrader** [comment]
I presume that the Dates package in Base has an abstract TimeType that parents Date and DateTime.

@quinnj ?

**Comment by GordStephen** [comment]
Yep, correct.

```julia
julia> subtypes(Dates.TimeType)
2-element Array{Any,1}:
 Base.Dates.Date    
 Base.Dates.DateTime
```

**Comment by milktrader** [comment]
Interesting. Starting to think about your interface above. It looks elegant and presumably solves the issue about supporting both Date and DateTime operations, no?

**Comment by GordStephen** [comment]
Yeah, exactly. It would also theoretically support any new or custom TimeTypes that were to come along in the future.

**Comment by milktrader** [comment]
Good point, like a `Ticktime` type maybe for high frequency trading

**Comment by GordStephen** [comment]
Added in #223
