### ISSUE TITLE
Merge behaviour when a single colname is erroneously supplied 

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#210]
The tests seem to indicate that the desired behaviour for `merge` is to have any renaming fail silently when supplied with a colname vector of length 1 (https://github.com/JuliaStats/TimeSeries.jl/blob/a8c28306520fd41289f64a9ca9e7947555899eb8/test/combine.jl#L21). Why shouldn't this throw an error instead? RIght now a 1-element vector seems to be a sentinel value for "nothing passed", but can't we use an empty vector for that?

**Comment by GordStephen** [comment]
Also, since `colnames` is the name of the relevant `TimeArray` type property and getter function, for consistency it might be good to use that as the `merge` keyword argument (instead of `col_names`).

**Comment by milktrader** [comment]
Yeah, I put in `col_names` because `colnames` is also a method. I'm open to a different name than `col_names` because I too don't like it.

**Comment by milktrader** [comment]
Also, about silent failing. Yeah, that's not so good. Do you think a warning would be best with the method executing? Something like "Column names argument ambiguous, names have not been changed"

**Comment by GordStephen** [comment]
To temporarily avoid breaking existing code, I think a warning would be ok, but ultimately maybe the method should just throw an error if the column count and length of the supplied names vector don't match?

Regarding col_names vs colnames, as long as `merge` doesn't use the colnames method, is there any harm in masking it in the local scope?

**Comment by milktrader** [comment]
iirc, using colnames in the `merge` method does create a collision.

**Comment by GordStephen** [comment]
A potential approach to addressing this is given in https://github.com/JuliaStats/TimeSeries.jl/pull/215/files#diff-be962d94e2313f96c9cd339a391addc0L9 (it throws an error when a length-one col_names array is passed).

**Comment by GordStephen** [comment]
The above approach was adopted with #223
