### ISSUE TITLE
0.6.3 tests are failing on the package repository

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#212]
http://pkg.julialang.org/logs/TimeSeries_0.4.log

Looks like the same issue as discussed in https://github.com/JuliaStats/TimeModels.jl/issues/48

**Comment by milktrader** [comment]
Ok, I'll fix this now.

**Comment by milktrader** [comment]
31e6f4103894b9b151f95cb9d7fa23634c4775cb

**Comment by milktrader** [comment]
Oops, jumped the gun here.

**Comment by milktrader** [comment]
I think I know what's going on now. I recently removed `using TimeSeries` outside of the MarketData module so it's not being imported like it had been previously.

**Comment by GordStephen** [comment]
Ah, ok - mystery solved!
