### ISSUE TITLE
Are coverage tests working?

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#216]
The [Coveralls.io results page](https://coveralls.io/github/JuliaStats/TimeSeries.jl) hasn't updated for a month and a half, did something break? The current Coverage.jl readme indicates .travis.yml needs:

```yml
after_success:
- julia -e 'cd(Pkg.dir("TimeSeries")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
```

which is missing.

**Comment by GordStephen** [comment]
Could also be that the testing call needs to enable coverage testing, e.g

```yml
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("TimeSeries"); Pkg.test("TimeSeries", coverage=true)'
```

**Comment by milktrader** [comment]
You PR fixes this, no? Re-open if not.
