### ISSUE TITLE
Proposed changes coming out in Version 0.7.0

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#218]
These are some important changes coming, mostly being developed by @GordStephen 

- [x] replace `Union{Date, DateTime}` with `TimeType` in the timestamp
- [x] improve the `merge` method to support more types of merges
- [x] add `NaN` as a missing, consumed value sentinel option until NullableArrays matures
- [x] streamline `lead` / `lag` API (#221)
- [x] rename `findall` to `find`(https://github.com/JuliaStats/TimeSeries.jl/pull/206#discussion_r39359627)
- [x] remove `meta` type parameter (#220) 

I would say that we keep with only supporting Julia 0.4.x with this version, and move to support Julia 0.5.x with TImeSeries 0.8.0

**Comment by milktrader** [comment]
@GordStephen you can of course edit the list above and add or modify entries.

**Comment by GordStephen** [comment]
Sounds good, will do.

**Comment by GordStephen** [comment]
All of the above now addressed in #223
