### ISSUE TITLE
Remove type information from the meta field

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#220]
I'm thinking in most cases, the meta field simply contains a string identifying the TimeArray. The parameterizing of that field seems over kill and is cluttering the API.

**Comment by GordStephen** [comment]
:+1: Should we look at changing this in 0.7.0?

**Comment by milktrader** [comment]
Yes. This should give this some time to stay an issue and see if anyone else has objection to it. I doubt anyone has leveraged type information in the meta field, but maybe.

**Comment by GordStephen** [comment]
Ok. Do we just make the `meta` field an `Any` or restrict it to something like `AbstractString`?

**Comment by milktrader** [comment]
How about no type at all? That's the same thing as `Any` no?

`AbstractString` is no good because you might put something in there that isn't a string but a custom type of some sort.

**Comment by GordStephen** [comment]
Ok, I just pushed https://github.com/JuliaStats/TimeSeries.jl/commit/0b16b55ad9ccaa59f13a3821f5ff91acb8a393ae which uses`Any` (same thing no type would imply).

**Comment by GordStephen** [comment]
Meta type parameter is removed in #223
