### ISSUE TITLE
Value types for percentchange

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeSeries.jl#225]
The various merge methods have been implemented to dispatch on a value type (e.g. `merge(ta1, ta2, Val{:left})`) - should `percentchange` follow this pattern?

For example, the API would change from

```julia
percentchange(ta, method="log")
```

to 

```julia
percentchange(ta, Val{:log})
```

This would avoid the need to evaluate the method kwarg at runtime and clean up the source.

I actually already implemented this in https://github.com/JuliaStats/TimeSeries.jl/commit/7d9398f6ecc1fc39e69983cd50013438dc1b72a7#diff-fcecd393d0e9b533ae6e5f1143cded5bR150, but can switch it back if the preference is to stick to the status quo.

**Comment by milktrader** [comment]
Hmm, I need to think about this. You're saying this new interface should be faster?

I need to read up on what this `Val{:log}` means.

**Comment by andreasnoack** [comment]
Isn't the return type the whether or not the log approximation is used? If that is the case, then there is no reason to use the `Val` type.

**Comment by GordStephen** [comment]
Ok, the API for the different `merge` methods should be revisited then. Is passing a string the most idiomatic way to chose from a finite set of possible functionalities for the same input (or should the method just be broken out into uniquely named functions)? In the case of `percentchange` a `log=true` kwarg would be fine too, although in `merge` that would create a bit of an ambiguous mess since there are more than two mutually exclusive options. `@enum` maybe?

**Comment by andreasnoack** [comment]
If a function has many arguments, it can be very useful with keyword arguments, but here I wouldn't use a keyword beause of the costs of using. Instead, I'd use a normal argument with a default value.

It is preferred to use `Symbol`s instead og strings because they are more efficient. If there is only two options then a `Bool` is also fine although it can be hard to remember if `true` means logarithm approximation or exact, but now that we have a documentation system in place that might not be a real concern anymore.

**Comment by milktrader** [comment]
This is a good case where `method="simple"` could be replaced with `Bool::log=false`. The documentation will need to be changed of course and it would be nice to add documentation ahead of the method code for online help.

**Comment by GordStephen** [comment]
Ok, so let's do this?

```julia
percentchange(ta::TimeArray; log::Bool=false)
merge(ta1, ta2, join::Symbol=:inner)
```

**Comment by GordStephen** [comment]
Also, now that I think about it, the variable name `method` kind of implies that the output should be the same, but the means to achieve it will be different, when in fact simple vs log produces different values altogether. But I guess if it's not a kwarg it's a moot point since the user doesn't see the name anyways.

**Comment by GordStephen** [comment]
Adopted `percentchange(ta::TimeArray, method::Symbol=:simple)` (and similar API for `merge` and `dropnan`) in #223.
