### ISSUE TITLE
Refactor "by" method

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#231]
- [x] make new `when` method period argument non-kwarg with a default value
- [x] re-order argument list in new `when` method to `TimeArray`,  `Function`, `Int or String`
- [x] allow interval argument to take a string (for `dayname` and `monthname`) -- both `by` and `when`
- [x]  write tests to cover all possible arguments
- [x] update NEWS
- [x] create deprecated.jl `src` and `test` files
- [x] create deprecation warnings
- [ ] ~~possibly not name the new method `when` but overload `Base.find` instead.~~ https://github.com/JuliaStats/TimeSeries.jl/issues/232

**Comment by milktrader** [comment]
How about change the name from `by` to `when`?

`when(cl, dayofweek, 4)`

almost read like English, "when my time series day of the week is 4"

@andreasnoack @multidis @GordStephen

**Comment by milktrader** [comment]
I'm adding this to the list above, and will sit on it for a bit to get some feedback ...

**Comment by milktrader** [comment]
Really liking `when`. Here's an example of use-case using the Watchmaker.jl package ...

````julia
using Watchmaker
c = yahoo()
cp = percentchange(c)
cpx = when(cp, dayname, "Friday") | x -> when(x, day, 13)
kplot(cpx)
````

**Comment by milktrader** [comment]
Ok, this is done, but I'm not sure about the name `when`. The more I think about the more I think we should just overload `Base.find` for this method, and while we're at it, replace `findwhen` to `find` as well as deprecate `findall`

**Comment by GordStephen** [comment]
`when` does have great readability. I guess using `find` depends on whether or not there's value in restricting that function's use to cases that are analogous to`Base.find` (i.e. `findall` but not `by`). What exactly is your concern with `when`?

**Comment by milktrader** [comment]
Thinking about this, `when` seems like a good fit.
