### ISSUE TITLE
find methods should return original time series

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#233]
This takes https://github.com/JuliaStats/TimeSeries.jl/issues/232 one step further. As of now, the `findwhen` and `findall` methods return a TimeArray of DateTime and Int, respectively. An easier to reason about interface would have them return the first argument TimeArray when the condition in additional arguments is satisfied. 

`find(ta::TimeArray, b::TimeArray{Bool})` would replace `findall` and `findwhen`.

`find(ta::TimeArray, f::Function, t::ASCIIString)` and `find(ta::TimeArray, f::Function, t::Int)` would replace `by`.

**Comment by GordStephen** [comment]
See my comment in #232 - my preference would be to keep `find` analagous to `Base.find` if possible. The current `by` is a sort of special case of `filter`, maybe we implement a TimeArray version of filter as a general solution and build out something on top of that for the common case where the filter predicate is `timestamp -> f(timestamp) == targetval`?

**Comment by GordStephen** [comment]
I guess to summarize my thoughts on all of this, my preference (maybe stemming from a bias for a functional programming style) would be to first implement general "primitive" TimeArray operations that directly extend functionality from `Base` and match its method names (find, filter, etc) and then build more specific syntactic-sugar-y methods to address common time-series-specific use cases (with more intuitive names) on top of those.

**Comment by milktrader** [comment]
Thanks for your logic here, I'll close this as a bad idea.
