### ISSUE TITLE
Version 0.6.x frozen at 0.6.7

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#235]
From here, we merge the 0.7.0 branch provided by @GordStephen

**Comment by milktrader** [comment]
I think the best way to do this is to simply merge the 0.7.0 branch. @GordStephen since you did the work, I'll let you decide to do this or I can do it.

**Comment by GordStephen** [comment]
Sure, I'll have some time this weekend to finalize things (on email right
now, but I seem to recall their being some last changes required?) and will
go ahead and merge it when those are done.

**Comment by milktrader** [comment]
Sounds good. When we get it polished we can tag 0.7.0.

**Comment by milktrader** [comment]
0.7.0 has been tagged.
