### ISSUE TITLE
readtimearray with arbitrary delimiters

### ISSUE THREAD

**Issue by dourouc05** [JuliaStats/TimeSeries.jl#238]
When trying to read external data, I face a problem as they are not exactly CSV: they use a semi-colon as delimiter. However, as it is now, readtimearray only understands CSV. My modification is quite simple: add a new parameter `dlm` (with default value `','` for compatibility), and use `readdlm` instead of `readcsv`. 

Hence the beginning of `readdlm` would become: 

    function readtimearray_own(fname::AbstractString; dlm=',', meta=nothing, format::AbstractString="")
        cfile = readdlm(fname, dlm)
        
        # remove empty lines if any

My full code (outside TimeSeries.jl sources) is: 

    function readtimearray_own(fname::AbstractString; dlm=',', meta=nothing, format::AbstractString="")
        function insertNaN{N}(aa::Array{Any,N})
            for i in 1:size(aa,1)
                for j in 1:size(aa,2)
                    if !isa(aa[i,j], Real)
                        aa[i,j] = NaN
                    end
                end
            end
            convert(Array{Float64,N},aa)
        end

        cfile = readdlm(fname, dlm)
        
        # remove empty lines if any
        inoempty = find(s -> length(s) > 2, cfile[:,1])
        cfile = cfile[inoempty,:]
        
        time  = cfile[2:end,1]
        if length(time[1]) < 11
            # assuming Date not DateTime
            format == "" ?
            tstamps = Date[Date(t) for t in time] :
            tstamps = Date[Date(t, format) for t in time]
        else
            format == "" ?
            tstamps = DateTime[DateTime(t) for t in time] :
            tstamps = DateTime[DateTime(t, format) for t in time]
        end 

        vals   = insertNaN(cfile[2:end, 2:end])
        cnames = UTF8String[]
        for c in cfile[1, 2:end]
            push!(cnames, c)
        end
        TimeArray(tstamps, vals, cnames, meta)
    end

(I don't know what's your preferred way of getting such fixes: via issues or directly pull requests?)

**Comment by milktrader** [comment]
Pull requests. Can you write some tests too? Also, not sure keyword `dlm` is a good choice. What does Base use?

**Comment by milktrader** [comment]
Here we go ...

`readdlm(source, delim::Char, T::Type; options...)` so for us we'd use `readtimearray(fname::AbstractString; delim::Char=',', meta=nothing, format::AbstractString="")`
