### ISSUE TITLE
Non-unique column names

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/TimeSeries.jl#255]
Since column names are used for indexing, I believe they'll have to be unique. That is not enforced right now. E.g.
```jl
julia> ts = TimeArray(collect(Date("2001-01-01"):Date("2001-01-20")), randn(20,2,2,2), ["TS1", "TS1"])
20x2 TimeSeries.TimeArray{Float64,4,Date,Array{Float64,4}} 2001-01-01 to 2001-01-20

             TS1     TS1     
2001-01-01 | 0.1279  -0.0751 
2001-01-02 | 0.2737  -0.469  
2001-01-03 | 1.0628  -0.9695 
2001-01-04 | 0.3766  0.2762  
⋮
2001-01-17 | -0.1788 0.947   
2001-01-18 | 0.5221  -0.8946 
2001-01-19 | -0.0433 1.5337  
2001-01-20 | 1.6569  -0.806  


julia> ts["TS1"]
20x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 2001-01-01 to 2001-01-20

             TS1     
2001-01-01 | 0.1279  
2001-01-02 | 0.2737  
2001-01-03 | 1.0628  
2001-01-04 | 0.3766  
⋮
2001-01-17 | -0.1788 
2001-01-18 | 0.5221  
2001-01-19 | -0.0433 
2001-01-20 | 1.6569  
```

I noticed this when merging two time series downloaded with `Quandl.jl`. The resulting `TimeArray` had repeated column names. The question is how to rename the columns. `DataFrames.jl` just appends with `_[number]`, but it would be great to use some information from the input arrays. However, the meta field is probably too generic to be useful here. Would it make sense to have a `name` field as well? In the case of time series downloaded with Quandl, the name field could be populated with the name information in the meta information Quandl attaches to the data. Maybe this could also be useful for e.g. plotting methods.

**Comment by GordStephen** [comment]
So with names you would get `ta1name_TS1`, `ta2name_TS1` as post-merge columns? That makes a lot of sense, databases often handle joins in a similar way. Would names be mandatory or would there be a good way of generating unique defaults (UUID-style)?

While we're at it, we would should probably switch colname lookups from linear search to a Dict.

**Comment by milktrader** [comment]
Yep, for starters column names should be unique.

**Comment by nalimilan** [comment]
Currently, DataFrames's `readtable` and `join` fonctions add `_1` to the second column, `_2` to the third, etc., when some column names are duplicated.

**Comment by milktrader** [comment]
I had this iterative naming implemented at some point and agree that's probably the best approach here. The next issue is to make that a constraint so this doesn't happen.

**Comment by milktrader** [comment]
Gotta admit I started hacking on this and it's more complicated than I thought!

**Comment by milktrader** [comment]
Scratchpad for later ...

````julia
function find_dupes_index(foo)
       x = Int[]
       for f in 1:length(foo)
       if contains(string(foo[1:f-1]), foo[f])
       push!(x, f)
       end
       end
       x
       end

function replace_dupes(foo)
       n=1
       while length(unique(foo)) != length(foo)

       ds = find_dupes_index(foo)

       for d in ds
       if n == 1
       foo[d] = string(foo[d], " $n")
       else
       foo[d] = string(foo[d][1:length(foo[d])-2], " $n")

       end

       end
       n +=1

       end
       foo
       end
````
