### ISSUE TITLE
Thoughts on a frequency/period attribute?

### ISSUE THREAD

**Issue by paulhendricks** [JuliaStats/TimeSeries.jl#256]
Including frequency/period as an attribute would open doors to functionality for up-sampling, down-sampling, and similar functionality provided in R's default way of handling time series objects or the way Pandas handles time series.

**Comment by milktrader** [comment]
Which R time series package do you use? The `xts` is the gold standard.

**Comment by milktrader** [comment]
The `collapse` method allows you to bring a more granular frequency to a larger frame. One period that hasn't been implemented yet in that method is `quarterly` and that would be a nice add.

**Comment by paulhendricks** [comment]
I'll have a look at the collapse method, it might solve my use case. 

I'm currently in the process of developing a package that does linear innovations state space modeling. One of the steps to initializing the state vector involves knowing how many seasonal components there, usually specified by the frequency or period. I've noticed that having a standard data structure that has frequency/period tied into a numeric array is nice and saves me having to pass frequency/period as a separate argument.

**Comment by milktrader** [comment]
Closing as `collapse` appears to handle this.
