### ISSUE TITLE
Timeseries merging with nanosecond precision

### ISSUE THREAD

**Issue by hgeorgako** [JuliaStats/TimeSeries.jl#263]
Trying to port over some of my quant code to Julia.  Currently using a hodgepodge of pandas, xts and Rcpp code to accomplish some fairly basic timeseries merging tasks.  What I would like to do is specify something like this: (xts in R does it, but not to nanosecond resolution).

x1
date_time, series_1
2016-05-18 08:30:03.123432, 103.23
2016-05-18 08:30:03.123434, 103.21
2016-05-18 08:30:03.123435, 103.25
...

x2
date_time, series_2
2016-05-18 08:30:03.123430, 86.21
2016-05-18 08:30:03.123434, 87.23
2016-05-18 08:30:03.123438, 85.21
...

x3 = merge(x1, x2)

date_time, series_1, series_2
2016-05-18 08:30:03.123430, NA, 86.21
2016-05-18 08:30:03.123432, 103.23, NA
2016-05-18 08:30:03.123434, 103.21, 87.23
2016-05-18 08:30:03.123435, 103.25, NA
2016-05-18 08:30:03.123438, NA, 85.21

**Comment by milktrader** [comment]
Do you have a small sample of nanosecond data that we can work with, I'd love to compete with xts! (btw, xts is an excellent package)

**Comment by hgeorgako** [comment]
Yes, xts is a wonderful package.  It's simple, with no bells and whistles and does exactly what's needed for timeseries analysis.

What's needed in Julia's version (And maybe this functionality exists. I haven't really looked at the other packages that are available), is:

1. Nanosecond merging as illustrated above
2. A rollapply() type paradigm similar to zoo's in R where one specifies a lambda function that can be evaluated over a set of observations.  It would be nice to allow these observations to be aggregated in time, and event-space. 

For example, given x1 as above, one could say something like this: 
   x_mean_time = roll(x1, n = 10, type = "seconds", lambda = mean) (this will aggregate in time space).
The type could be "years", "months", "days", "hours", "minutes", "seconds", "microseconds", "nanoseconds". 
   x_mean_obs = roll(x1, n = 10, type = "obs", lambda = mean) (this will aggregate in event space).
n = 10, means get the last 10 values.

One has to figure out what to do with the NA's. In R, you can simply omit them, interpolate them, etc. 

Again, I apologize if this stuff is obvious to the Julia folks.  Just something that would make life for quant/traders way easier.

**Comment by milktrader** [comment]
Since TimeSeries depends on Base.Dates for DateTime precision, this issue would be better filed in base Julia.
