### ISSUE TITLE
Default naming of columns

### ISSUE THREAD

**Issue by femtotrader** [JuliaStats/TimeSeries.jl#265]
Here is some code

```julia
start = Date(2000,1,30)
periods = 9
freq = Dates.Day(1)
dates = start:start + (periods - 1) * freq
mytime = TimeArray(collect(dates), rand(length(dates)), ["col1"])
mytime3 = TimeArray(collect(dates), rand(length(dates), 3), ["col1", "col2", "col3"])
```

maybe `TimeArray` could be build without specifying column names

I also notice that `collect` is necessary... maybe it could be done inside constructor ?

**Comment by milktrader** [comment]
Yep, I think I'll do this one. I'll close this since I opened the same issue just now. https://github.com/JuliaStats/TimeSeries.jl/issues/266

**Comment by femtotrader** [comment]
Thanks... english is not my mother tongue!
