### ISSUE TITLE
Rename TimeArray to TimeFrame

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#268]
This has been discussed before and there have been some arguments in favor of abandoning the `Array` moniker. This opens up room for new data structures too, such as `TimeVector`.

The problem though is that `Frame` is clearly associated with `DataFrame` but the `TimeFrame` type would only hold homogenous types.

I don't really like `TimePanel` but open to the idea if there is an overwhelming preference.

**Comment by milktrader** [comment]
This clearly breaks all the code written for `TimeArray` but tagging a new minor release should mitigate breakage.

**Comment by milktrader** [comment]
We might also include TimeArray in the deprecated.jl file, which should work for constructors.

**Comment by femtotrader** [comment]
This was discussed in https://github.com/JuliaStats/TimeSeries.jl/issues/262

I wouldn't use the term "Panel" which is use to design 3D data in Python Pandas.

I'd prefer a `TimeSerie` and a `TimeFrame`

**Comment by femtotrader** [comment]
A TimeSerie being composed of 
 - an array of datetime and
 - an 1D array of values

a TimeFrame being composed of
 - an array of datetime and
 - several arrays of values

**Comment by milktrader** [comment]
`TimeSerie` won't work. First I'm not sure it's even a word and second it lays too large a claim on the idea of TimeSeries.

**Comment by milktrader** [comment]
I think if someone really wants a `DataFrame` with a date/datetime element then they should simply create a 'DateFrame' with one added.

As far as TimePanel, there is not obligation to follow Pandas.

**Comment by milktrader** [comment]
TimeFrames.jl has been registered by METADATA so this is no longer feasible.
