### ISSUE TITLE
dayofweek/dayname not defined

### ISSUE THREAD

**Issue by yangguang760** [JuliaStats/TimeSeries.jl#277]
I tried to run the example given by the document, julia throws error as below:

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating TradingLogic...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using TimeSeries

julia> using MarketData

julia> when(cl, dayofweek, 1)
ERROR: UndefVarError: dayofweek not defined

**Comment by quinnj** [comment]
those functions are part of Base.Dates, so you'll need to do
```
using Base.Dates
```
first

**Comment by milktrader** [comment]
Yeah this is annoying. The documentation in `getting started` doesn't specify `using Base.Dates` and we might as well place the `using Base.Dates` call outside the module. Can't remember when/why we took it out.

**Comment by milktrader** [comment]
Options:

1. Reflect this requirement in documentation
2. Import the `Base.Dates` module

**Comment by quinnj** [comment]
Yeah, I think we need to either put the call to `using Base.Dates` outside the module, better document that you need to do it yourself, or using the `Reexport.jl` package to reexport all of `Base.Dates`.

**Comment by milktrader** [comment]
How crazy is it to just export `Base.Dates` methods and DataTypes instead of everything by adding `Reexport.jl`, which I'd rather not do.

**Comment by quinnj** [comment]
Not too crazy. Just everything [here](https://github.com/JuliaLang/julia/blob/master/base/dates/Dates.jl)

**Comment by milktrader** [comment]
I like this idea. I've put those exports into a file named `src/Base.Dates.jl` and simply added an `include Base.Dates.jl` in the module (to keep things neat.

I'm worried the excellent coverage we have with tests will go down, but it's like getting a scratch on a new car. Nobody likes it but you can live with it.

**Comment by milktrader** [comment]
I think it's fair to expect to have `Base.Dates` methods and such available in a package named `TimeSeries`

**Comment by milktrader** [comment]
`dayofweek` isn't on that list ... curious, no?
