### ISSUE TITLE
Enable update to work on empty TimeArrays

### ISSUE THREAD

**Issue by ElevatorDeLuxe** [JuliaStats/TimeSeries.jl#283]
Hello, everybody!

I have the following issue:
If you create an empty TimeArray and then call an update, you receive an error.

Example:
`time_array = TimeArray(Vector{Date}(), Array{Float64}(0))`
`update(time_array, Date(2000,1,1), 42.0)`
results in the error
`ERROR: ArgumentError: reducing over an empty collection is not allowed
 in _mapreduce at reduce.jl:139
 in update at /home/user/.julia/v0.4/TimeSeries/src/modify.jl:14`

The option to update an empty TimeArray would be quite handy. Maybe I find the time to fix it myself. I would then commit a pull request.

Best regards Thomas

**Comment by milktrader** [comment]
Why would you rather update an empty TimeArray versus creating it?

If you update an empty TimeArray, you first need to create it and then update it versus just creating the TimeArray with values from the update to begin with.

**Comment by milktrader** [comment]
The code to support this would be simple ...
````julia
elseif length(ta) == 0
    TimeArray(tstamp, val)
else 
...
````

**Comment by ElevatorDeLuxe** [comment]
Okay. I think this depends on the definition of creation. I would say 
` time_array = TimeArray(Vector{Date}(), Array{Float64}(0)) `
is already creating it even it it is empty. For the workflow of a function that returns a TimeArray, that can potentially be empty, this would be a nice feature.

`function returnTimeArray(someParams...)`
`   time_array = TimeArray(Vector{Date}(), Array{Float64}(0))`
`   some_logic_that_adds_entries(time_array, someParams...)` # possibly no entries are added
`   return time_array`
`end`

**Comment by ElevatorDeLuxe** [comment]
Commited pull request #285 .

**Comment by milktrader** [comment]
This was closed as won't fix.
