### ISSUE TITLE
test/timearray.jl throws error for undefined variable

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#284]
The intent of the test is to check that invariants are enforced but in fact it's throwing errors for other reasons.

https://github.com/JuliaStats/TimeSeries.jl/commit/42fc178eccbad57d098b50b6dafbcebd7a3d2380#commitcomment-19011849

**Comment by milktrader** [comment]
Also, we need to change `push` back to `push!` in both the dupestamp and mangstamp tests. Not sure why it was changed, but it happened recently (as it since support for 0.5 was introduced)

**Comment by tkelman** [comment]
I merged https://github.com/JuliaLang/METADATA.jl/pull/6353 anyway since hopefully these are test-only issues.

**Comment by milktrader** [comment]
Yep, they are. Thanks @tkelman I'll clean this up soon.
