### ISSUE TITLE
Create TimeArray from array of compound type

### ISSUE THREAD

**Issue by femtotrader** [JuliaStats/TimeSeries.jl#287]
Hello,

I have defined a compound type like

```julia
type Position
  Date::DateTime
  x::AbstractFloat
  y::AbstractFloat
  z::AbstractFloat
end
```

An array of compound type is defined like this

```julia
arr = [Position(DateTime(2016,1,1,10,00,00),0,0,0),
       Position(DateTime(2016,1,1,10,00,01),2,0,0),
       Position(DateTime(2016,1,1,10,00,02),2,1,0),
       Position(DateTime(2016,1,1,10,00,03),2,2,0),
       ]
```

I'd like to build a `TimeArray` from `arr`

I can easily get `a_Dates` (array of dates) using

```julia
a_Dates = map(rec->rec.Date, arr)
```

but I don't know how to get a 4x3 (x, y, z) array to build a `TimeArray`

Maybe TimeSeries could build directly TimeArray from array of compound type
(given field name of Date).

Same suggestion for iterators of compound type.

**Comment by milktrader** [comment]
Why not just use the x,y,z coordinate values as a row in an array?

````julia
julia> dts = [DateTime(2016,1,1,10,00,00)
              DateTime(2016,1,1,10,00,01)
              DateTime(2016,1,1,10,00,02)
              DateTime(2016,1,1,10,00,03)]
4-element Array{DateTime,1}:
 2016-01-01T10:00:00
 2016-01-01T10:00:01
 2016-01-01T10:00:02
 2016-01-01T10:00:03

julia> positions = [0 0 0 
                    2 0 0
                    2 1 0
                    2 2 0]
4×3 Array{Int64,2}:
 0  0  0
 2  0  0
 2  1  0
 2  2  0
julia> TimeArray(dts, positions, ["x", "y", "z"])
4x3 TimeSeries.TimeArray{Int64,2,DateTime,Array{Int64,2}} 2016-01-01T10:00:00 to 2016-01-01T10:00:03

                      x       y       z       
2016-01-01T10:00:00 | 0       0       0       
2016-01-01T10:00:01 | 2       0       0       
2016-01-01T10:00:02 | 2       1       0       
2016-01-01T10:00:03 | 2       2       0       
````

**Comment by femtotrader** [comment]
Because I have data in an Array of Positions.
see http://stackoverflow.com/questions/39560340/convert-a-1-dimensional-array-of-objects-compound-type-to-a-2-dimensional-arra/39567901#39567901

**Comment by milktrader** [comment]
Ok.

This is not really an issue with this package, but a programming/coding question. I'll give you an idea, but I'm closing this as a question better suited for SO or Julia users mailing list.

````julia
julia> function get_values{T<:Position}(ap::Array{T})
       vals = ones(length(ap), 3)
       for i in 1:length(ap)
           vals[i,:] = [ap[i].x ap[i].y ap[i].z]
       end
       vals
       end
WARNING: Method definition get_values(Array{#T<:Main.Position, N<:Any}) in module Main at REPL[209]:2 overwritten at REPL[212]:2.
get_values (generic function with 1 method)

julia> get_values(arr)
4×3 Array{Float64,2}:
 0.0  0.0  0.0
 2.0  0.0  0.0
 2.0  1.0  0.0
 2.0  2.0  0.0
````

**Comment by femtotrader** [comment]
Thanks

Pandas have an interesting function for this kind of use case (and more general) named `json_normalize`

http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.io.json.json_normalize.html

**Comment by milktrader** [comment]
That appears to be a DataFrame constructor from a JSON object, rather than a time series constructor for an un-defined custom type.

**Comment by femtotrader** [comment]
Yes, you are right but a similar approach may also fit with TimeSeries
