### ISSUE TITLE
Push 0.9.1 to METADATA

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#293]
This was tagged several weeks ago and I still haven't resolved my issue with using `PkgDev` to publish it. 😞

**Comment by andreasnoack** [comment]
What is the issue?

**Comment by milktrader** [comment]
It was previously documented and related to unable to fast-forward. I'm working on it now. I have deleted the entire `0.5.0` folder and re-installed packages. This may have fixed things but `PkdDev.publish()` for some reason doesn't see a new tag on TimeSeries (0.9.1).

**Comment by milktrader** [comment]
````julia
julia> PkgDev.publish()
ERROR: There are no METADATA changes to publish
 in (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/Administrator/.julia/v0.5/PkgDev/src/entry.jl:72
 in with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /Users/Administrator/.julia/v0.5/PkgDev/src/entry.jl:64
 in publish() at /Users/Administrator/.julia/v0.5/PkgDev/src/PkgDev.jl:70
````

**Comment by milktrader** [comment]
This is probably because I deleted the folder, let me see if I can retag

**Comment by milktrader** [comment]
Fixed my issues. There must have been some bug in a pre-release of 0.5.0- that corrupted the v0.5 folder. In any case, deleting the folder fixed it.

**Comment by andreasnoack** [comment]
Remember to remove the remote tag

**Comment by milktrader** [comment]
I locally deleted the tag and pushed that and then later tagged with the PkgDev.tag() method so it should be good, unless you see something suspicious
