### ISSUE TITLE
Generalised lag and lead? 

### ISSUE THREAD

**Issue by dourouc05** [JuliaStats/TimeSeries.jl#310]
Both `lag` and `lead` seem to be designed to work with daily time series (as per the documentation), with the number of days being a parameter to these functions (`Int`). However, the code does not make this assumption. 

I am thinking of a slight generalisation of these functions: instead of taking an integer parameter, they would take a `Period` object (such as `Day(1)` or `Month(1)`), which would automatically be converted in the right number of shifts to perform. 

That operation is not complicated per se, but I think it would make the API easier to use. If there is no opinion against this, I can implement it.

**Comment by milktrader** [comment]
What happens if you lag or lead over a weekend day in your typical financial time series?

**Comment by milktrader** [comment]
So what happens if you lag 1 `day` and the time series doesn't include weekends?

**Comment by milktrader** [comment]
Closing for now.
