### ISSUE TITLE
InexactError() when data is not of type Float64

### ISSUE THREAD

**Issue by bluesmoon** [JuliaStats/TimeSeries.jl#318]
Using Julia 0.4.5 and TimeSeries 0.8.8

If you create a `TimeArray` with the following type:

`TimeSeries.TimeArray{Int64,2,DateTime,Array{Int64,2}}`

And then try to call `moving` on it, you get the following error:

```
InexactError()

 in convert at int.jl:209
 in moving at /home/ubuntu/.julia/v0.4/TimeSeries/src/apply.jl:224
```

If you instead typecast your array to `Array{Float64}` in the constructor, then `moving` works as expected.

I think two things need to be fixed here:

1. The error message needs to be a little clearer.  Just `InexactError` says nothing
2. The function should do automatic type conversion for compatible types

**Comment by ararslan** [comment]
I believe 1 is a limitation of Julia 0.4. Once 0.6 is released, 0.4 will receive only critical bugfixes in Base, and I think it's unlikely that package authors will continue to support 0.4. (Indeed, it seems most have already dropped support, including this package, which currently requires 0.5 at a minimum.) If this is still an issue with Julia 0.5 and the most recent release of TimeSeries, it should be addressed, but I'd be surprised if anyone was willing to go through the trouble of backporting a change to a TimeSeries release that supports 0.4.
