### ISSUE TITLE
Plotting TimeSeries Julia v. 0.6

### ISSUE THREAD

**Issue by HamletFr** [JuliaStats/TimeSeries.jl#323]
The following minimal code gives an error:

using TimeSeries
dates = collect(Date(1999,1,1):Date(2000,12,31))
mytime = TimeArray(dates, rand(length(dates)))
plot(mytime)

the error message reads as follows:

ArgumentError: Millisecond: 63050832000000 out of range (0:999)

Could you help me?

**Comment by iblis17** [comment]
Hi @HamletFr 
could you give master branch a try?
PR #321 got merged a week ago.

```julia
julia> Pkg.status("TimeSeries")
 - TimeSeries                    0.10.0
julia> Pkg.checkout("TimeSeries")
...
julia> Pkg.status("TimeSeries")
 - TimeSeries                    0.10.0+            master
```

**Comment by juanbono** [comment]
Hi! I tried to code above and it works making a small change:
```julia
using TimeSeries, Plots
dates = collect(Date(1999,1,1):Day(1):Date(2000,12,31))
mytime = TimeArray(dates, rand(length(dates)))
plot(mytime)
```
