### ISSUE TITLE
Convert TimeSeries back into array

### ISSUE THREAD

**Issue by samjurl** [JuliaStats/TimeSeries.jl#364]
Hi,

This is not an issue, just a question: is it possible to convert the TimeSeries back into an array somehow? Such that the element types can be recognized and used by Julia directly.

Basically I have made a series of calculations to end up with a TimeSeries of Boolean values, and would like to use those in conditional statements which require direct Booleans.

Best,
Sam

**Comment by iblis17** [comment]
There is a field `values`.
You can access it via `ta.values`; to accessing the time line, `ta.timestamp`.

**Comment by samjurl** [comment]
Perfect, thanks.
