### ISSUE TITLE
Enable FemtoCleaner

### ISSUE THREAD

**Issue by femtotrader** [JuliaStats/TimeSeries.jl#367]
Hello,

I did https://github.com/JuliaStats/TimeSeries.jl/pull/365 but [FemtoCleaner](https://github.com/JuliaComputing/FemtoCleaner.jl) doesn't seem to start.

Could you ensure it's currently installed?

Kind regards

**Comment by iblis17** [comment]
@ararslan I do not have the permission. 
Could you check FemtoCleaner?

**Comment by ararslan** [comment]
FemtoCleaner is enabled for all JuliaStats repositories so I'm not sure why it wasn't triggered. @Keno?

**Comment by Keno** [comment]
You need to update REQUIRE.

**Comment by Keno** [comment]
Oh sorry, you currently also need to make the PR from the same repository that FemtoCleaner is enabled one, otherwise it can't see it (I complained to GitHub about that already).

**Comment by iblis17** [comment]
https://github.com/JuliaStats/TimeSeries.jl/pull/370/checks
I also tried to trigger Femtocleaner. The request :point_up: has been queued over 20 hrs. Any idea?

**Comment by iblis17** [comment]
It works in #370 now.
