### ISSUE TITLE
Moving: functions with multiple inputs

### ISSUE THREAD

**Issue by versipellis** [JuliaStats/TimeSeries.jl#401]
Is there a way to use `moving` with functions with multiple args? For example, I want to use `stdm` from `Statistics`. The function's args is as follows:
```
stdm(v, m; corrected::Bool=true)
```
It doesn't seem to be that there's a way in `moving` to do so at the moment.

**Comment by iblis17** [comment]
So... in your case, is the input `m` known prior to `moving`?

**Comment by iblis17** [comment]
I guess you want `moving` function with a whole row as an input?

**Comment by iblis17** [comment]
Idea: `moving(...; dims = 2)`

**Comment by iblis17** [comment]
closed via #415
