### ISSUE TITLE
TimeArray printing return error in too small terminal

### ISSUE THREAD

**Issue by ValentinKaisermayer** [JuliaStats/TimeSeries.jl#428]
Hello,
if the terminal window is too small (e.g. VSCode) trying to print a TimeArray results in an obscure error.

> ERROR: BoundsError: attempt to access 0-element view(::Array{DateTime,1}, Int64[]) with eltype DateTime at index [1]

**Comment by iblis17** [comment]
(cc me)

**Comment by iblis17** [comment]
well, what is the actual size of your terminal? It can be checked by `displaysize`.

```julia
julia> displaysize(stdout)
(36, 147)
```

**Comment by ValentinKaisermayer** [comment]
```julia
julia> displaysize(stdout)
(9, 218)
```

**Comment by ValentinKaisermayer** [comment]
it seems to stem from this:
```julia
drow, dcol = displaysize(io)
res_row    = 9  # number of reserved rows: summary line, label line ... etc
half_row   = floor(Int, (drow - res_row) / 2)
add_row    = (drow - res_row) % 2
```

So `half_row` and `add_row` are <= 0.
