### ISSUE TITLE
Label is ignored in plot

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaStats/TimeSeries.jl#430]
If a `TimeArray` is plotted the `label` argument of `plot` seems to be ignored.
```julia
using TimeSeries
using Dates
using Plots

dates = Date(2018, 1, 1):Day(1):Date(2018, 12, 31)
ta = TimeArray(dates, rand(length(dates)), [:rand])

p = plot(ta, label="new label")
```
Thanks!

**Comment by ohmsweetohm1** [comment]
The problem seems to be here: https://github.com/JuliaStats/TimeSeries.jl/blob/8b00a78cf276948d3a57980356340b289d8e5156/src/plotrecipes.jl#L10

**Comment by iblis17** [comment]
oh, so we can make it as a default to allow user-defined value.

@ohmsweetohm1 Could you make a PR and test it?
```julia
labels -> get(plotattributes, :label, reshape(String.(colnames(ta)),1,length(colnames(ta))) )
```
