### ISSUE TITLE
Plotting TimeArray with seriestype == :candlestick causes exception "UndefVarError: find not defined"

### ISSUE THREAD

**Issue by Sh4pe** [JuliaStats/TimeSeries.jl#432]
When plotting a `TimeArray` using `seriestype = :candlestick`, I get the following exception:

```
UndefVarError: find not defined
```

caused at [plotrecipes.jl:27](https://github.com/JuliaStats/TimeSeries.jl/blob/v0.16.0/src/plotrecipes.jl#L27). I'm using v0.16.0 of TimeSeries.jl and Julia 1.12. Indeed, the function `find` is not defined. The code in `plotrecipes.jl` seems not to have changed between v0.16.0 and `master`.

**Comment by iblis17** [comment]
Hi @Sh4pe could you open a PR about that?
`find` -> `findall`.

**Comment by Sh4pe** [comment]
Ok, I will. Thanks for the advice!
