### ISSUE TITLE
plotting with Plotly is semi-broken

### ISSUE THREAD

**Issue by Moelf** [JuliaStats/TimeSeries.jl#461]
![image](https://user-images.githubusercontent.com/5306213/89698598-18ea9980-d8f0-11ea-94c4-297fdf872d14.png)
```
Plots v1.5.8
TimeSeries v0.18.0
```

**Comment by iblis17** [comment]
:man_facepalming: 
I need time to figure out the Plot.jl issue.
I'm working on Gadfly.jl support: https://github.com/GiovineItalia/Gadfly.jl/pull/1215. Maybe you can try this branch out first

**Comment by Moelf** [comment]
no worries, I know Plots (recipes) can be suck to work with sometime. thx for the good work!

**Comment by iblis17** [comment]
Hi @Moelf , I just rewrite the plot recipe for candlestick.
Could you try PR #464 out?

**Comment by Moelf** [comment]
![image](https://user-images.githubusercontent.com/5306213/89933669-65c6bc80-dbdd-11ea-97e2-4ab0ca8badea.png)

wow, thanks for the swift reaction.

It looks like the hover is gone completely? and the x-axis is too granular I think

**Comment by Moelf** [comment]
let me give you this for testing:
```
using DataFrames, TimeSeries, Dates, Plots

m = [ 1.83    1.8708  1.83    1.84     5351.0
        1.85    1.85    1.7688  1.7701  12854.0
        1.75    1.8869  1.75    1.8201  15735.0
        1.795   1.82    1.78    1.78    24814.0
        1.76    1.8578  1.76    1.8299   6539.0
        1.8159  1.8709  1.7973  1.8309   7422.0
        1.79    1.87    1.7899  1.87    18386.0
        1.88    1.88    1.79    1.79     7768.0
        1.78    1.8     1.6785  1.75    18711.0
        1.71    1.79    1.71    1.7892  16594.0]

df = DataFrame(m, [:open, :high, :low, :close, :volume])
df.ts = (now()-Day(9)):Day(1):now()

df_ts = TimeArray(df, timestamp=:ts)

plotly()
plot(df_ts, st=:candlestick)
```

**Comment by iblis17** [comment]
> It looks like the hover tooltips is gone completely? 

What kind of information do you expect to show on the tooltips?
Since I rewrite the recipe, there is a chance that we can decide the content of tooltips.

> and the x-axis is too granular I think

well, I'm still searching about the `xticks` auto-shrinking method from Plots.

**Comment by Moelf** [comment]
if I look for inspiration on some online candle plots, for example [yahool](https://finance.yahoo.com/chart/GE#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJ0aW1lVW5pdCI6bnVsbCwiY2FuZGxlV2lkdGgiOjYxLjc3MjcyNzI3MjcyNzI3LCJmbGlwcGVkIjpmYWxzZSwidm9sdW1lVW5kZXJsYXkiOnRydWUsImFkaiI6dHJ1ZSwiY3Jvc3NoYWlyIjp0cnVlLCJjaGFydFR5cGUiOiJjYW5kbGUiLCJleHRlbmRlZCI6ZmFsc2UsIm1hcmtldFNlc3Npb25zIjp7fSwiYWdncmVnYXRpb25UeXBlIjoib2hsYyIsImNoYXJ0U2NhbGUiOiJsaW5lYXIiLCJwYW5lbHMiOnsiY2hhcnQiOnsicGVyY2VudCI6MC44LCJkaXNwbGF5IjoiR0UiLCJjaGFydE5hbWUiOiJjaGFydCIsImluZGV4IjowLCJ5QXhpcyI6eyJuYW1lIjoiY2hhcnQiLCJwb3NpdGlvbiI6bnVsbH0sInlheGlzTEhTIjpbXSwieWF4aXNSSFMiOlsiY2hhcnQiLCLigIx2b2wgdW5kcuKAjCJdfSwi4oCMdm9sdW1l4oCMIjp7InBlcmNlbnQiOjAuMiwiZGlzcGxheSI6IuKAjHZvbHVtZeKAjCIsImNoYXJ0TmFtZSI6ImNoYXJ0IiwiaW5kZXgiOjEsInlBeGlzIjp7Im5hbWUiOiLigIx2b2x1bWXigIwiLCJwb3NpdGlvbiI6bnVsbH0sInlheGlzTEhTIjpbXSwieWF4aXNSSFMiOlsi4oCMdm9sdW1l4oCMIl19fSwic2V0U3BhbiI6eyJtdWx0aXBsaWVyIjoxLCJiYXNlIjoibW9udGgiLCJwZXJpb2RpY2l0eSI6eyJwZXJpb2QiOjEsImludGVydmFsIjoiZGF5In19LCJsaW5lV2lkdGgiOjIsInN0cmlwZWRCYWNrZ3JvdW5kIjp0cnVlLCJldmVudHMiOnRydWUsImNvbG9yIjoiIzAwODFmMiIsInN0cmlwZWRCYWNrZ3JvdWQiOnRydWUsImV2ZW50TWFwIjp7ImNvcnBvcmF0ZSI6eyJkaXZzIjp0cnVlLCJzcGxpdHMiOnRydWV9LCJzaWdEZXYiOnt9fSwiY3VzdG9tUmFuZ2UiOm51bGwsInN5bWJvbHMiOlt7InN5bWJvbCI6IkdFIiwic3ltYm9sT2JqZWN0Ijp7InN5bWJvbCI6IkdFIiwicXVvdGVUeXBlIjoiRVFVSVRZIiwiZXhjaGFuZ2VUaW1lWm9uZSI6IkFtZXJpY2EvTmV3X1lvcmsifSwicGVyaW9kaWNpdHkiOjEsImludGVydmFsIjoiZGF5IiwidGltZVVuaXQiOm51bGwsInNldFNwYW4iOnsibXVsdGlwbGllciI6MSwiYmFzZSI6Im1vbnRoIiwicGVyaW9kaWNpdHkiOnsicGVyaW9kIjoxLCJpbnRlcnZhbCI6ImRheSJ9fX1dLCJzdHVkaWVzIjp7IuKAjHZvbCB1bmRy4oCMIjp7InR5cGUiOiJ2b2wgdW5kciIsImlucHV0cyI6eyJpZCI6IuKAjHZvbCB1bmRy4oCMIiwiZGlzcGxheSI6IuKAjHZvbCB1bmRy4oCMIn0sIm91dHB1dHMiOnsiVXAgVm9sdW1lIjoiIzAwYjA2MSIsIkRvd24gVm9sdW1lIjoiI2ZmMzMzYSJ9LCJwYW5lbCI6ImNoYXJ0IiwicGFyYW1ldGVycyI6eyJ3aWR0aEZhY3RvciI6MC40NSwiY2hhcnROYW1lIjoiY2hhcnQiLCJwYW5lbE5hbWUiOiJjaGFydCJ9fSwi4oCMdm9sdW1l4oCMIjp7InR5cGUiOiJ2b2x1bWUiLCJpbnB1dHMiOnsiaWQiOiLigIx2b2x1bWXigIwiLCJkaXNwbGF5Ijoi4oCMdm9sdW1l4oCMIn0sIm91dHB1dHMiOnsiVXAgVm9sdW1lIjoiIzhjYzE3NiIsIkRvd24gVm9sdW1lIjoiI2I4MmMwYyJ9LCJwYW5lbCI6IuKAjHZvbHVtZeKAjCIsInBhcmFtZXRlcnMiOnsiY2hhcnROYW1lIjoiY2hhcnQiLCJwYW5lbE5hbWUiOiLigIx2b2x1bWXigIwifX19fQ--) they hover a window on top left for high, low, open, close; so I guess we can default to display those 4 as well on hover.

**Comment by iblis17** [comment]
I update the PR and add the hover text.

also, I made the density of xticks controlled by `xticks::Int` .
e.g.
```
plot(ta, st = :candlestick, xrotation = 60, xticks = 3)
```
![newplot](https://user-images.githubusercontent.com/761623/89990265-ad6c4780-dcb4-11ea-8182-77d8ea67a5ee.png)

**Comment by iblis17** [comment]
BTW, we have `MarketData.yahoo` in the latest version.

```
ta = MarketData.yahoo(:GE, YahooOpt(period1 = now() - Month(2), period2 = now()))
plot(ta, st = :candlestick, xrotation = 60, xticks = 3)
```

**Comment by Moelf** [comment]
ah, thanks, this looks much better now!

**Comment by Moelf** [comment]
https://plotly.com/python/candlestick-charts/

btw, while we're at it, is it possible to have the sliding window at the bottom as well? i'm looking to integrate with `Dash.jl` maybe it's something I need to do for `Dash` specifically but I really would like to use TimeSeries instead of manually construct stuff, https://github.com/plotly/Dash.jl/issues/50

**Comment by iblis17** [comment]
> https://plotly.com/python/candlestick-charts/

JS version is here: https://plotly.com/javascript/candlestick-charts/#simple-candlestick-chart

> btw, while we're at it, is it possible to have the sliding window at the bottom as well? i

If I understand correctly, in order to support native candlestick from Plotly and get the sliding window,
we have to modify stuffs in `Plots.plotly_series`, since the JS doc of Plotly shows that the argument `type: "candlestick"` should go with `Plots.plotly_series`  (the var `plotattributes_out[:type]`).

https://github.com/JuliaPlots/Plots.jl/blob/47590b2538b9d0387b14d46eb49e7257f904dde6/src/backends/plotly.jl#L535-L579

> i'm looking to integrate with Dash.jl maybe it's something I need to do for Dash specifically but I really would like to use TimeSeries instead of manually construct stuff, plotly/Dash.jl#50

I think there are two option to get the native support of candlestick from Plotly,
1. Add `Plots` native support for Plotly banckend only, and let other `seriestype = :candlestick` fallback to our recipe. (not sure the fallback is possible or not)
2. Add `TimeArray` support for `PlotlyJS.jl` (but I never use that package before, also need time to figure out)

**Comment by Moelf** [comment]
>     1. Add `Plots` native support for Plotly banckend only, and let other `seriestype = :candlestick` fallback to our recipe. (not sure the fallback is possible or not)

I'm fine with using `TimeSeries` to extend the recipe when plotting, but I assumed this would give me the correct layout etc. when calling `Plots.plotly_series` on the result plot but it wasn't quite right

**Comment by iblis17** [comment]
> I'm fine with using TimeSeries to extend the recipe when plotting, but I assumed this would give me the correct layout etc. when calling Plots.plotly_series on the result plot but it wasn't quite right

well, I'm not quite sure what you mean.

In short. The interactive sliding window of Plotly isn't possible to construct by a plot recipe. It need some changes in `Plots.plotly_series`.

**Comment by Moelf** [comment]
ah, I see what you mean. Well, then I guess that's the extend to can do for this issue, thanks for your time and effort of fixing it!
