### ISSUE TITLE
`moving` with dims=2 with an easy way to distinguish the columns

### ISSUE THREAD

**Issue by itchingpixels** [JuliaStats/TimeSeries.jl#490]
Hi!
I have a usecase, where I'd need to go over a 2D TimeSeries, and would want to easily select / identify a col within the passed in function.
It looks like when I set `dims = 2` I get an array with the following dimensions passed in: `(<window>, <cols>)`.

I'm experimenting with writing a custom `moving` function for my needs, here are a couple of things I'm debating about:
- One thing I could do is pass in a TimeArray instead of a SubArray. I assume this would be quite ineffective, as TimeArray would copy the contents of the SubArray for every period.
- Maybe to use something like NamedArray.jl? to name the columns. not sure if NamedArray copies the array its constructed with...
Or do you have any recommendation?:)

Thanks!

**Comment by iblis17** [comment]
I think the NamedTuple is fine for your case?

**Comment by itchingpixels** [comment]
thanks for the help, yes, I think that's a good bet!
