### ISSUE TITLE
collapse to quarter

### ISSUE THREAD

**Issue by sellingsrud** [JuliaStats/TimeSeries.jl#501]
Quarterly data is prevalent in social science, it'd be useful with a collapse(x, quarter) method.

**Comment by sellingsrud** [comment]
Perfect, that's exactly the functionality I needed.

Maybe it's already there? I only checked "quarter" and looked at the list in the docs. Sorry about that

**Comment by iblis17** [comment]
ah, I will update the doc.

**Comment by iblis17** [comment]
I just recall https://github.com/JuliaStats/TimeSeries.jl/issues/498#issue-932229197.
So,  this might be more accurate:
```
collapse(cl, Dates.quarter, first, mean)
```
