### ISSUE TITLE
Really inefficient printing for large TimeArrays

### ISSUE THREAD

**Issue by ValentinKaisermayer** [JuliaStats/TimeSeries.jl#514]
The main source seems to be this line:

https://github.com/JuliaStats/TimeSeries.jl/blob/0356f4bbad7e7f7b6a8cacde04f0948a65fd4ed4/src/timearray.jl#L297

only a very small subset of `strs` is used later.

**Comment by ValentinKaisermayer** [comment]
Also if a TimeArray is a field of a struct the whole TimeArray is printed. Is there no summary view?

**Comment by piechologist** [comment]
Regarding large TimeArrays, I put the following code in my `startup.jl`:

```
using TimeSeries
Base.show(io::IO, ::MIME"text/plain", ta::TimeArray) = if length(ta) > 6
    println("Showing only the head of ", length(ta), " rows…")
    show(io, head(ta))
else
    show(io, ta)
end
```

It's just my personal preference as I usually have many rows but relatively few columns.
